# cpp-netlib Project Travis CI configuration.

language: cpp
os: linux
dist: trusty
sudo: false

cache:
  - apt
  - ccache

matrix:
  include:
    # GCC configurations
    - env: BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release" ENABLE_HTTPS="ON" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES CC=gcc-4.9 CXX=g++-4.9
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["g++-4.9", "libboost1.55-all-dev"] } }
    - env: BUILD_SHARED_LIBS="ON" CMAKE_BUILD_TYPE="Release" ENABLE_HTTPS="OFF" Uri_BUILD_TESTS=OFF Uri_DISABLE_LIBCXX=YES CC=gcc-4.9 CXX=g++-4.9
      addons: { apt: { sources: ["ubuntu-toolchain-r-test"], packages: ["g++-4.9", "libboost1.55-all-dev"] } }

install:
  - pwd
  - export CUR_DIR=`pwd`
  - mkdir -p ${CUR_DIR}/bin

before_script:
  - echo ${CXX}
  - "${CXX} --version"
  - echo ${CC}
  - "${CC} --version"

script:
  - pwd
  - sh -x build.sh

after_failure:
  - cat build/Testing/Temporary/LastTest.log

notifications:
  slack:
    secure: Y7lLjqZ83+b/jaJ5+EKwvgCDeERi4bVbDn9tLp8sieTdu+ENsPI+JmLYSXZXPpe7JrItrXW6uJJXN2wG1h7au4mpVVTghd31HBzuzrqVxDphWPhp16NYzvbAgQQRBXvFVvfSdW/Kb/n2fX6xDApY0t6vNREb/GKg0GyzESb4ZjU=
